import { useEffect, useState } from 'react'
import { ArrowRight, Check, ChevronDown, Menu, Minus, Plus, Search, ShoppingBag, Sparkles, Store, Truck, X } from 'lucide-react'
import { supabase } from './supabase'
import { api } from './api'

const demoItems = [
 {id:'demo-1',name:'Everyday Cotton Kurti',category_name:'Women',category_slug:'women',vendor_name:'Sample local seller',vendor_id:'demo-vendor',price:'699',compare_at_price:'999',image_url:'https://images.unsplash.com/photo-1583391733956-6c78276477e4?auto=format&fit=crop&w=900&q=85',sizes:['S','M','L','XL'],colors:['Rose','Cream'],stock_quantity:10,description:'Soft breathable cotton with a relaxed everyday fit.'},
 {id:'demo-2',name:'Classic Linen Shirt',category_name:'Men',category_slug:'men',vendor_name:'Sample local seller',vendor_id:'demo-vendor',price:'849',compare_at_price:'1199',image_url:'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=900&q=85',sizes:['M','L','XL'],colors:['Sand','Olive'],stock_quantity:8,description:'A versatile shirt for workdays and weekends.'},
 {id:'demo-3',name:'Festive Printed Dress',category_name:'Women',category_slug:'women',vendor_name:'Sample local seller',vendor_id:'demo-vendor',price:'1199',compare_at_price:'1499',image_url:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=900&q=85',sizes:['S','M','L'],colors:['Blue','Maroon'],stock_quantity:6,description:'A vibrant silhouette made for family celebrations.'},
 {id:'demo-4',name:'Kids Weekend Set',category_name:'Kids',category_slug:'kids',vendor_name:'Sample local seller',vendor_id:'demo-vendor',price:'549',compare_at_price:'699',image_url:'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=900&q=85',sizes:['2Y','4Y','6Y'],colors:['Yellow','Sky'],stock_quantity:15,description:'Comfort-first style for active little days.'},
 {id:'demo-5',name:'Handloom Festive Saree',category_name:'Ethnic Wear',category_slug:'ethnic-wear',vendor_name:'Sample local seller',vendor_id:'demo-vendor',price:'1899',compare_at_price:'2399',image_url:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=85',sizes:['Free size'],colors:['Wine','Emerald'],stock_quantity:4,description:'Traditional-inspired colour with a graceful drape.'},
 {id:'demo-6',name:'Minimal Crossbody Bag',category_name:'Accessories',category_slug:'accessories',vendor_name:'Sample local seller',vendor_id:'demo-vendor',price:'499',compare_at_price:'649',image_url:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=85',sizes:['One size'],colors:['Tan','Black'],stock_quantity:11,description:'A compact everyday bag for your essentials.'}
]
const defaultCats = [{id:'all',name:'All styles',slug:'all'},...['Women','Men','Kids','Ethnic Wear','Accessories'].map((name,i)=>({id:name.toLowerCase(),name,slug:['women','men','kids','ethnic-wear','accessories'][i]}))]
const money = n => `₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`

export default function App() {
 const [session,setSession]=useState(null),[profile,setProfile]=useState(null)
 const [products,setProducts]=useState([]),[categories,setCategories]=useState(defaultCats)
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState('all')
 const [cart,setCart]=useState([]),[selected,setSelected]=useState(null),[size,setSize]=useState(''),[color,setColor]=useState('')
 const [drawer,setDrawer]=useState(''),[menu,setMenu]=useState(false),[toast,setToast]=useState(''),[orders,setOrders]=useState([])
 const [busy,setBusy]=useState(false),[address,setAddress]=useState({recipient_name:'',phone:'',line1:'',line2:'',landmark:'',city:'Rayachoty',state:'Andhra Pradesh',postal_code:'',notes:''})
 const [productForm,setProductForm]=useState({name:'',description:'',price:'',compare_at_price:'',category_id:'',vendor_id:'',image_url:'',image_public_id:'',sizes:'S,M,L,XL',colors:'Black,Blue',stock_quantity:'1'})
 const demo=import.meta.env.VITE_DEMO_MODE==='true'
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const {data}=supabase.auth.onAuthStateChange((_,s)=>{setSession(s);if(!s)setProfile(null)});return()=>data.subscription.unsubscribe()},[])
 useEffect(()=>{if(!session){setProfile(null);return}api('/profile/',{token:session.access_token}).then(setProfile).catch(()=>setProfile({role:'customer'}))},[session])
 useEffect(()=>{load()},[category,search,demo])
 async function load(){setLoading(true);try{const q=new URLSearchParams();if(category!=='all')q.set('category',category);if(search.trim())q.set('search',search.trim());const [p,c]=await Promise.all([api(`/products/?${q}`),api('/categories/').catch(()=>defaultCats.slice(1))]);setProducts(p.results||p);setCategories([defaultCats[0],...c]);setError('')}catch(e){if(demo){setProducts(demoItems.filter(p=>(category==='all'||p.category_slug===category)&&`${p.name} ${p.category_name}`.toLowerCase().includes(search.toLowerCase())));setError('')}else{setProducts([]);setError('Store API is not connected yet. Deploy the Django backend and set VITE_API_BASE_URL.')}}finally{setLoading(false)}}
 function notify(t){setToast(t);window.setTimeout(()=>setToast(''),2600)}
 async function login(){if(!supabase)return notify('Set Supabase frontend environment variables first.');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)notify(error.message)}
 async function logout(){await supabase?.auth.signOut();setDrawer('');notify('Signed out')}
 const count=cart.reduce((n,p)=>n+p.quantity,0),subtotal=cart.reduce((n,p)=>n+Number(p.price)*p.quantity,0)
 const vendors=[...new Set(cart.map(p=>p.vendor_id||p.vendor_name))]
 function add(p,s=p.sizes?.[0]||'',c=p.colors?.[0]||''){const key=`${p.id}:${s}:${c}`;setCart(old=>old.some(i=>i.key===key)?old.map(i=>i.key===key?{...i,quantity:Math.min(i.quantity+1,Number(i.stock_quantity||20))}:i):[...old,{...p,key,quantity:1,size:s,color:c}]);setSelected(null);setDrawer('cart');notify('Added to your bag')}
 async function getOrders(){if(!session)return login();try{const r=await api('/orders/',{token:session.access_token});setOrders(r.results||r);setDrawer('orders')}catch(e){notify(e.message)}}
 async function uploadImage(file){
  if(!file||!session)return notify('Sign in with an approved vendor/admin account first.')
  setBusy(true)
  try{
   const sign=await api('/uploads/signature/',{method:'POST',token:session.access_token,body:JSON.stringify({folder:'bala-fashion/products'})})
   const form=new FormData()
   Object.entries(sign.params).forEach(([k,v])=>form.append(k,v))
   form.append('api_key',sign.api_key);form.append('signature',sign.signature);form.append('file',file)
   const response=await fetch(`https://api.cloudinary.com/v1_1/${sign.cloud_name}/image/upload`,{method:'POST',body:form})
   const data=await response.json()
   if(!response.ok)throw new Error(data.error?.message||'Cloudinary upload failed')
   setProductForm(p=>({...p,image_url:data.secure_url,image_public_id:data.public_id}))
   notify('Image uploaded to Cloudinary')
  }catch(e){notify(e.message)}finally{setBusy(false)}
 }
 async function saveProduct(e){
  e.preventDefault();if(!session)return login();setBusy(true)
  try{
   await api('/products/manage/',{method:'POST',token:session.access_token,body:JSON.stringify({...productForm,price:Number(productForm.price),compare_at_price:productForm.compare_at_price?Number(productForm.compare_at_price):null,stock_quantity:Number(productForm.stock_quantity),sizes:productForm.sizes.split(',').map(x=>x.trim()).filter(Boolean),colors:productForm.colors.split(',').map(x=>x.trim()).filter(Boolean)})})
   setProductForm({name:'',description:'',price:'',compare_at_price:'',category_id:'',vendor_id:'',image_url:'',image_public_id:'',sizes:'S,M,L,XL',colors:'Black,Blue',stock_quantity:'1'})
   await load();setDrawer('');notify('Product saved')
  }catch(e){notify(e.message)}finally{setBusy(false)}
 }
 async function place(e){e.preventDefault();if(!session)return login();if(vendors.length>1)return notify('Checkout one seller at a time.');setBusy(true);try{const r=await api('/orders/',{method:'POST',token:session.access_token,body:JSON.stringify({address,notes:address.notes,items:cart.map(i=>({product_id:i.id,quantity:i.quantity,size:i.size,color:i.color}))})});setCart([]);setOrders(o=>[r,...o]);setDrawer('orders');notify(`Order ${r.order_number} placed`)}catch(err){notify(err.message)}finally{setBusy(false)}}
 return <div className="site">
  <div className="topline"><span>Local fashion, thoughtfully picked</span><span><Truck size={14}/> Delivery across Rayachoty <b>•</b> Cash on delivery</span></div>
  <header className="header">
   <button className="icon mobile" onClick={()=>setMenu(!menu)} aria-label="Menu"><Menu/></button>
   <button className="brand" onClick={()=>{setCategory('all');window.scrollTo({top:0,behavior:'smooth'})}}><span className="logo">BF</span><span><b>BALA FASHION</b><small>RAYACHOTY · ANDHRA PRADESH</small></span></button>
   <nav className={menu?'nav nav-open':'nav'}><button onClick={()=>{setCategory('all');setMenu(false)}}>Shop all</button>{categories.filter(c=>c.slug!=='all').slice(0,4).map(c=><button key={c.slug} onClick={()=>{setCategory(c.slug);setMenu(false)}}>{c.name}</button>)}</nav>
   <div className="head-actions"><label className="search"><Search size={16}/><input placeholder="Search styles" value={search} onChange={e=>setSearch(e.target.value)}/></label><button className="icon signin" onClick={()=>session?setDrawer('account'):login()}>{session?.user?.user_metadata?.avatar_url?<img src={session.user.user_metadata.avatar_url} alt="Profile"/>:'Sign in'}</button><button className="bag" onClick={()=>setDrawer('cart')}><ShoppingBag size={19}/><span>Bag</span><b>{count}</b></button></div>
  </header>
  <main>
   <section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> YOUR LOCAL STYLE DESTINATION</div><h1>Good style.<br/><em>Closer to home.</em></h1><p>Discover everyday favourites, festive finds and independent sellers from around Rayachoty — all in one place.</p><div className="hero-cta"><button className="primary" onClick={()=>document.getElementById('collection').scrollIntoView({behavior:'smooth'})}>Explore collection <ArrowRight size={16}/></button><span><Check size={15}/> Local sellers. Easy COD.</span></div></div>
    <div className="hero-art"><img className="hero-main" src="https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1000&q=90" alt="Friends browsing fashion"/><img className="hero-small" src="https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=700&q=85" alt="Curated clothing"/><div className="stamp"><small>STYLE</small><b>LOCAL</b><small>LOVE</small></div><div className="caption">● New season, new favourites</div></div>
   </section>
   <section className="promises"><div><Store/><span><b>Local sellers</b><small>Discover nearby boutiques</small></span></div><div><Truck/><span><b>Rayachoty delivery</b><small>Convenient local drop-off</small></span></div><div><Check/><span><b>Cash on delivery</b><small>Pay when it arrives</small></span></div></section>
   <section className="collection" id="collection"><div className="section-head"><div><div className="eyebrow muted">THE EDIT</div><h2>Find your <em>favourite.</em></h2><p>Pieces for everyday moments and special occasions.</p></div><span className="section-note">CURATED FOR YOU <ChevronDown size={14}/></span></div>
    <div className="chips">{categories.map(c=><button className={category===c.slug?'chip active':'chip'} key={c.slug} onClick={()=>setCategory(c.slug)}>{c.name}</button>)}</div>
    {error&&<div className="notice">{error}<button onClick={load}>Retry</button></div>}
    {demo&&<div className="demo">Preview mode — sample products only, not live inventory. Set <code>VITE_DEMO_MODE=false</code> for production.</div>}
    <div className="grid">{loading?Array.from({length:6},(_,i)=><div className="skeleton" key={i}><div/></div>):products.map((p,i)=><article className="product" key={p.id}><button className="photo" onClick={()=>{setSelected(p);setSize(p.sizes?.[0]||'');setColor(p.colors?.[0]||'')}}>{p.image_url?<img src={p.image_url} alt={p.name} loading={i>2?'lazy':'eager'}/>:<span className="placeholder">BF</span>}{p.compare_at_price&&Number(p.compare_at_price)>Number(p.price)&&<small className="sale">SPECIAL PRICE</small>}<span className="quick">Quick view <ArrowRight size={13}/></span></button><div className="product-info"><div className="meta"><span>{p.category_name||'Curated style'}</span><span>{p.vendor_name||'Local seller'}</span></div><button className="product-name" onClick={()=>{setSelected(p);setSize(p.sizes?.[0]||'');setColor(p.colors?.[0]||'')}}>{p.name}</button><div className="price"><b>{money(p.price)}</b>{p.compare_at_price&&Number(p.compare_at_price)>Number(p.price)&&<del>{money(p.compare_at_price)}</del>}<button onClick={()=>add(p)} aria-label="Add to bag"><Plus size={18}/></button></div></div></article>)}</div>
    {!loading&&!products.length&&<div className="empty"><ShoppingBag size={27}/><h3>Your next favourite is on its way.</h3><p>No products match this view yet. Check another category or come back soon.</p><button className="secondary" onClick={()=>{setCategory('all');setSearch('')}}>See all styles</button></div>}
   </section>
   <section className="local"><div className="local-mark">BF</div><div><div className="eyebrow">MADE FOR OUR TOWN</div><h2>Rayachoty looks good on you.</h2><p>Support local fashion sellers and find something that feels like you.</p></div><button onClick={()=>notify('Seller onboarding: contact the store administrator.')}>Become a seller <ArrowRight size={16}/></button></section>
  </main>
  <footer><div className="footer-brand"><span className="logo">BF</span><span><b>BALA FASHION</b><small>RAYACHOTY · ANDHRA PRADESH</small></span></div><p>Local style, delivered with care.</p><small>© {new Date().getFullYear()} Bala Fashion Rayachoty</small></footer>
  {drawer&&<div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&setDrawer('')}><aside className="drawer"><div className="drawer-head"><div><div className="eyebrow muted">{drawer==='cart'?'YOUR SELECTION':drawer==='checkout'?'DELIVERY DETAILS':drawer==='orders'?'YOUR ACCOUNT':'BALA FASHION'}</div><h2>{({cart:'Your bag',checkout:'Checkout',orders:'My orders',account:'Account'})[drawer]||'Manage products'}</h2></div><button className="icon" onClick={()=>setDrawer('')}><X/></button></div>
   {drawer==='cart'&&<div className="drawer-body">{!cart.length?<div className="empty"><ShoppingBag/><h3>Your bag is taking a break.</h3><p>Find a piece you love and add it here.</p><button className="primary" onClick={()=>setDrawer('')}>Keep exploring</button></div>:<>{cart.map(i=><div className="cart-item" key={i.key}><img src={i.image_url} alt=""/><div><b>{i.name}</b><small>{i.size} {i.color&&`· ${i.color}`}</small><strong>{money(i.price)}</strong><div className="qty"><button onClick={()=>setCart(c=>c.map(x=>x.key===i.key?{...x,quantity:Math.max(1,x.quantity-1)}:x))}><Minus size={13}/></button>{i.quantity}<button onClick={()=>setCart(c=>c.map(x=>x.key===i.key?{...x,quantity:Math.min(Number(x.stock_quantity||20),x.quantity+1)}:x))}><Plus size={13}/></button><button className="remove" onClick={()=>setCart(c=>c.filter(x=>x.key!==i.key))}>Remove</button></div></div></div>)}{vendors.length>1&&<div className="warning">Please check out one seller at a time.</div>}<div className="summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><small>Cash on delivery · Rayachoty service area</small><button className="primary full" disabled={vendors.length>1} onClick={()=>session?setDrawer('checkout'):login()}>Continue to checkout <ArrowRight size={16}/></button></div></>}</div>}
   {drawer==='checkout'&&<form className="drawer-body form" onSubmit={place}><p>Where should we deliver your order?</p>{[['recipient_name','Recipient name'],['phone','Mobile number'],['line1','House / street address'],['line2','Address line 2 (optional)'],['landmark','Landmark'],['city','City'],['postal_code','PIN code']].map(([key,label])=><label key={key}>{label}<input required={!['line2','landmark','postal_code'].includes(key)} value={address[key]} onChange={e=>setAddress({...address,[key]:e.target.value})}/></label>)}<label>Delivery notes<textarea rows="2" value={address.notes} onChange={e=>setAddress({...address,notes:e.target.value})}/></label><div className="cod"><Check size={17}/><span><b>Cash on delivery</b><small>Pay in cash when your order arrives.</small></span></div><div className="summary"><div><span>Total</span><b>{money(subtotal)}</b></div><button className="primary full" disabled={busy}>{busy?'Placing order…':'Place COD order'} <ArrowRight size={16}/></button></div></form>}
   {drawer==='orders'&&<div className="drawer-body">{!session?<div className="empty"><p>Sign in to see your orders.</p><button className="primary" onClick={login}>Continue with Google</button></div>:!orders.length?<div className="empty"><h3>No orders yet</h3><button className="secondary" onClick={getOrders}>Refresh orders</button></div>:orders.map(o=><div className="order" key={o.id}><div><b>{o.order_number}</b><small>{o.status?.replaceAll('_',' ')}</small></div><p>{new Date(o.created_at).toLocaleDateString('en-IN')} · COD</p><strong>{money(o.total)}</strong></div>)}</div>}
   {drawer==='account'&&<div className="drawer-body"><p>{session?.user?.user_metadata?.full_name||session?.user?.email}</p><p className="muted">{profile?.role||'customer'}</p><button className="secondary full" onClick={getOrders}>View my orders</button>{['vendor','admin'].includes(profile?.role)&&<button className="primary full" onClick={()=>setDrawer('manage')}>Manage products</button>}<button className="text" onClick={logout}>Sign out</button></div>}
   {drawer==='manage'&&<form className="drawer-body form" onSubmit={saveProduct}><p>Add a product to your approved store.</p>
    <label>Product name<input required value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})}/></label>
    <label>Description<textarea rows="3" value={productForm.description} onChange={e=>setProductForm({...productForm,description:e.target.value})}/></label>
    <label>Approved vendor ID<input required value={productForm.vendor_id} onChange={e=>setProductForm({...productForm,vendor_id:e.target.value})} placeholder="Vendor UUID"/></label>
    <label>Category<select required value={productForm.category_id} onChange={e=>setProductForm({...productForm,category_id:e.target.value})}><option value="">Choose category</option>{categories.filter(c=>c.slug!=='all').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
    <div className="form-two"><label>Price (₹)<input required type="number" min="0" step="0.01" value={productForm.price} onChange={e=>setProductForm({...productForm,price:e.target.value})}/></label><label>Compare price<input type="number" min="0" step="0.01" value={productForm.compare_at_price} onChange={e=>setProductForm({...productForm,compare_at_price:e.target.value})}/></label></div>
    <label>Product image (Cloudinary)<input type="file" accept="image/*" onChange={e=>uploadImage(e.target.files?.[0])}/></label>{productForm.image_url&&<img className="upload-preview" src={productForm.image_url} alt="Uploaded product preview"/>}
    <label>Sizes (comma separated)<input value={productForm.sizes} onChange={e=>setProductForm({...productForm,sizes:e.target.value})}/></label><label>Colours (comma separated)<input value={productForm.colors} onChange={e=>setProductForm({...productForm,colors:e.target.value})}/></label>
    <label>Stock quantity<input required type="number" min="0" value={productForm.stock_quantity} onChange={e=>setProductForm({...productForm,stock_quantity:e.target.value})}/></label>
    <button className="primary full" disabled={busy}>{busy?'Saving…':'Save product'}</button></form>}
  </aside></div>}
  {selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="modal"><button className="icon close" onClick={()=>setSelected(null)}><X/></button><div className="modal-photo"><img src={selected.image_url} alt={selected.name}/></div><div className="modal-info"><div className="eyebrow muted">{selected.category_name||'CURATED STYLE'}</div><h2>{selected.name}</h2><small>Sold by {selected.vendor_name||'a local seller'}</small><h3>{money(selected.price)} {selected.compare_at_price&&<del>{money(selected.compare_at_price)}</del>}</h3><p>{selected.description||'A thoughtfully selected piece for your wardrobe.'}</p>{selected.sizes?.length>0&&<div className="options"><b>Choose size</b><div>{selected.sizes.map(s=><button className={size===s?'selected':''} key={s} onClick={()=>setSize(s)}>{s}</button>)}</div></div>}{selected.colors?.length>0&&<div className="options"><b>Choose colour</b><div>{selected.colors.map(c=><button className={color===c?'selected':''} key={c} onClick={()=>setColor(c)}>{c}</button>)}</div></div>}<button className="primary full" onClick={()=>add(selected,size,color)}><ShoppingBag size={16}/> Add to bag — {money(selected.price)}</button><small className="delivery"><Truck size={14}/> Local delivery · Cash on delivery</small></div></section></div>}
  {toast&&<div className="toast"><Check size={16}/>{toast}</div>}
 </div>
}
