-- Core marketplace schema; this matches the tables already created in the connected project.
create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default '',phone text not null default '',role text not null default 'customer' check(role in('customer','vendor','admin')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.vendors(id uuid primary key default gen_random_uuid(),owner_id uuid references auth.users(id) on delete set null,name text not null,slug text not null unique,description text not null default '',logo_url text not null default '',phone text not null default '',address text not null default '',status text not null default 'pending' check(status in('pending','approved','rejected','suspended')),created_at timestamptz not null default now());
create table if not exists public.categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,image_url text not null default '',sort_order int not null default 0,is_active boolean not null default true,created_at timestamptz not null default now());
create table if not exists public.products(id uuid primary key default gen_random_uuid(),vendor_id uuid not null references public.vendors(id) on delete restrict,category_id uuid references public.categories(id) on delete set null,name text not null,slug text not null unique,description text not null default '',price numeric(12,2) not null check(price>=0),compare_at_price numeric(12,2) check(compare_at_price is null or compare_at_price>=price),sku text not null default '',image_url text not null default '',image_public_id text not null default '',sizes text[] not null default '{}',colors text[] not null default '{}',stock_quantity int not null default 0 check(stock_quantity>=0),is_active boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.customer_addresses(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,recipient_name text not null,phone text not null,line1 text not null,line2 text not null default '',landmark text not null default '',city text not null default 'Rayachoty',state text not null default 'Andhra Pradesh',postal_code text not null default '',is_default boolean not null default false,created_at timestamptz not null default now());
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_number text not null unique,customer_id uuid not null references auth.users(id) on delete restrict,vendor_id uuid not null references public.vendors(id) on delete restrict,status text not null default 'placed' check(status in('placed','confirmed','packed','out_for_delivery','delivered','cancelled')),payment_method text not null default 'cod' check(payment_method='cod'),payment_status text not null default 'pending' check(payment_status in('pending','paid','refunded')),subtotal numeric(12,2) not null check(subtotal>=0),delivery_fee numeric(12,2) not null default 0 check(delivery_fee>=0),total numeric(12,2) not null check(total>=0),address_snapshot jsonb not null,notes text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.order_items(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id) on delete cascade,product_id uuid references public.products(id) on delete set null,product_name text not null,image_url text not null default '',size text not null default '',color text not null default '',quantity int not null check(quantity>0),unit_price numeric(12,2) not null check(unit_price>=0),line_total numeric(12,2) not null check(line_total>=0));
create index if not exists products_active_category_idx on public.products(is_active,category_id);
create index if not exists products_vendor_idx on public.products(vendor_id);
create index if not exists products_category_idx on public.products(category_id);
create index if not exists vendors_owner_idx on public.vendors(owner_id);
create index if not exists orders_customer_created_idx on public.orders(customer_id,created_at desc);
create index if not exists orders_vendor_created_idx on public.orders(vendor_id,created_at desc);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists order_items_product_idx on public.order_items(product_id);
create index if not exists addresses_user_idx on public.customer_addresses(user_id);
alter table public.profiles enable row level security;
alter table public.vendors enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
grant select on public.vendors,public.categories,public.products to anon,authenticated;
grant select,insert,update on public.profiles to authenticated;
grant select,insert,update,delete on public.customer_addresses to authenticated;
grant select on public.orders,public.order_items to authenticated;
drop policy if exists "Public can view approved vendors" on public.vendors;
create policy "Public can view approved vendors" on public.vendors for select to anon,authenticated using(status='approved');
drop policy if exists "Public can view active categories" on public.categories;
create policy "Public can view active categories" on public.categories for select to anon,authenticated using(is_active=true);
drop policy if exists "Public can view active products from approved vendors" on public.products;
create policy "Public can view active products from approved vendors" on public.products for select to anon,authenticated using(is_active=true and exists(select 1 from public.vendors v where v.id=vendor_id and v.status='approved'));
drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile" on public.profiles for select to authenticated using((select auth.uid())=id);
drop policy if exists "Users can create own profile" on public.profiles;
create policy "Users can create own profile" on public.profiles for insert to authenticated with check((select auth.uid())=id);
drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
drop policy if exists "Users manage own addresses" on public.customer_addresses;
create policy "Users manage own addresses" on public.customer_addresses for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
drop policy if exists "Users can view own orders" on public.orders;
create policy "Users can view own orders" on public.orders for select to authenticated using((select auth.uid())=customer_id);
drop policy if exists "Users can view own order items" on public.order_items;
create policy "Users can view own order items" on public.order_items for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.customer_id=(select auth.uid())));
insert into public.categories(name,slug,sort_order) values('Women','women',1),('Men','men',2),('Kids','kids',3),('Ethnic Wear','ethnic-wear',4),('Accessories','accessories',5) on conflict(slug) do nothing;
